socialProject/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"

urlpatterns = [
    
        path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
        path('signup/', views.SignUp.as_view(), name = 'signup'),
]

socialProject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path('new/', views.CreatePost.as_view(), name="create"),
    path('by/<str:username>/', views.UserPost.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name="single"),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name="delete")
]

socialProject/socialProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.testpage, name="test"),
    path('thanks/', views.thankspage, name="thanks"),
    path('groups/', include('groups.urls', namespace="groups")),
    path('posts/', include('posts.urls', namespace="posts")),
]

socialProject/templates/Index.html
{% extends "base.html" %}

{% block bodyblock %}
	<h1>Welcome to pReddit!</h1>
{% endblock %}

socialProject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title> pReddit! </title>

			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

			<link rel="stylesheet" href='{% static 'css/main.css' %}'>
	</head>
	<body>
		<nav role="navigation" class="navbar mynav" id="navbar">
			<div class="main-container">
				<a class="navbar-brand mynav-item mynav-brand" href="{% url 'home' %}">pReddit!</a>

				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
						<li><a class="navbar mynav-item" href="{% url 'posts:create' %}">Post</a></li>
						<li><a class="navbar mynav-item" href="{% url 'groups:all' %}">Groups</a></li>
						<li><a class="navbar mynav-item" href="{% url 'groups:create' %}">Create Group</a></li>
						<li><a class="navbar mynav-item" href="{% url 'accounts:logout' %}">Logout</a></li>
					{% else %}
						<li><a class="navbar mynav-item" href="{% url 'groups:all' %}">Groups</a></li>
						<li><a class="navbar mynav-item" href="{% url 'accounts:login' %}">Log In</a></li>
						<li><a class="navbar mynav-item" href="{% url 'accounts:signup' %}">Sign Up</a></li>
					{% endif %}
				</ul>
			</div>
		</nav>
		<div class="main-container">
			{% block bodyblock %}
			{% endblock %}
		</div>
	</body>
</html>

socialProject/templates/test.html
{% extends "base.html" %}

{% block bodyblock %}

<h1> You are now logged in!</h1>

{% endblock %}

socialProject/templates/thanks.html
{% extends "base.html" %}

{% block bodyblock %}

<h1> Thanks for visiting, come back soon! </h1>

{% endblock %}