socialProject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path('new/', views.CreatePost.as_view(), name="create"),
    path('by/<str:username>/', views.UserPost.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name="single"),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name="delete")
]

socialProject/socialProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.testpage, name="test"),
    path('thanks/', views.thankspage, name="thanks"),
    path('groups/', include('groups.urls', namespace="groups")),
    path('posts/', include('posts.urls', namespace="posts")),
]

socialProject/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model

import misaka

from groups.models import Group

User = get_user_model()

class Post(models.Model):

    user = models.ForeignKey(User, related_name='posts', on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=256)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("post:single", kwargs={"username": self.user.username,
                                              "pk": self.pk})
    
    class Meta:
        unique_together = ("user", "message")
        ordering = ["-created_at"]

socialProject/posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib.auth import get_user_model

from braces.views import SelectRelatedMixin

from . import models
from . import forms

User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')
    template_name = "posts/post_list.html"

class UserPost(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist :
            raise Http404
        else:
            return self.post_user.posts.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user 
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset =  super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    model = models.Post
    fields = ('title','message','group')
    success_url = reverse_lazy("posts:all")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user 
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy("posts:all")    

    def get_queryset(self):
        queryset =  super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)
      
    

socialProject/posts/templates/posts/_post.html
<div class="post media list-group-item">
    <h3>{{post.title}}</h3>
    <div class="media-body">
        <h5 class="media-heading">
            Written by :
            <span class="username">
                <a href="{% url 'posts:for_user' username=post.user.username  %}">@{{post.user.username}}</a>
            </span>
        </h5>
    </div>

    <div class="media-footer">
        {% if user.is_authenticated and post.user == user %}
            <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-danger">
                <span class='glyphicon glyphicon-remove'></span>
                <span class="icon-label">Delete</span>
            </a>
        {% endif %}
    </div>
</div>

socialProject/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block bodyblock %}

<div class="post-page">
    <div class="container">
        <div class="row">
            {% block prepost %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block postpost %}{% endblock %}
        </div>
    </div>
</div>

{% endblock %}

socialProject/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}

    <h3>Are you sure you want to delete this post?</h3>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">
            <span class='glyphicon glyphicon-remove'></span>
            <span class="icon-label">Yes, Delete</span>
        </button>
        <a href="{% url 'posts:single' username=user.username pk=post.pk %}" class="btn btn-primary">
            No, Cancel
        </a>
    </form>

{% endblock %}

socialProject/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block prepost %}
{% endblock %}


{% block post_content %}
    <div class="col-md-10">
        <h3>{{post.title}}</h3>
        <div class="media-body">
            <h4 class="media-heading">
                Author :
                <span class="username">
                    <a href="{% url 'posts:for_user' username=post.user.username  %}">@{{post.user.username}}</a>
                </span>
            </h4>
        </div>

        <hr>
        <div class="media-body">
            <p>
                {{post.message_html|safe}}
            </p>
        </div>
        <hr>

        <div class="media-footer">
            {% if user.is_authenticated and post.user == user %}
                <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-danger">
                    <span class='glyphicon glyphicon-remove'></span>
                    <span class="icon-label">Delete</span>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}


{% block postpost %}
{% endblock %}

socialProject/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}

<h1>Create a new Post</h1>

<form id="post-form-id" action="{% url 'posts:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Post" class="btn btn-primary btn-large" />
<form>

{% endblock %}

socialProject/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}

    <div class="col-md-4">
        {% if user.is_authenticated %}
               <div class="card card-with-shadow">
                    <div class="content">
                        <h4 class="title">Your Groups : </h4>
                        <ul class="list-unstyled">
                            {% for member_group in get_user_groups %}
                                <li class="group li-with-bullet" > 
                                    <a href="{% url 'groups:single' slug=member_group.group.slug %}">
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
               </div>
        {% endif %}

        <div class="card card-with-shadow">
            <div class="content">
                <h4 class="title">Other Groups : </h4>
                <ul class="list-unstyled">
                    {% for other_group in get_other_groups %}
                        <li class="group li-with-bullet" > 
                            <a href="{% url 'groups:single' slug=member_group.slug %}">
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

{% block post_content %}

    <div class="col-md-10">
        <div class="list-group">
            {% for post in object_list %}
                {% include "posts/_post.html" %}
            {% endfor %}
        </div>
    </div>

{% endblock %}

socialProject/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
    <div class="col-md-4">
        <div class="media-body">
            <h2 class="media-heading">
                <span class="username">
                    <a href="{% url 'posts:for_user' username=post_user.username  %}">@{{post_user.username}}</a>'s Posts
                </span>
            </h3>
        </div>
    </div>

{% endblock %}

<br>

{% block post_content %}

    <div class="col-md-10">
        <div class="list-group">
            {% for post in object_list %}
                <div class="post media list-group-item">
                    <h3>{{post.title}}</h3>
                    <div class="media-footer">   
                        <div class="row">
                            <div class="col-md-8">
                                Group : <a href="{% url 'groups:single' slug=post.group.slug %}">@{{post.group}}</a>
                            </div>
                            {% if user.is_authenticated and post_user == user %}
                                <div class="col-md-4">
                                    <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-danger">
                                        <span class='glyphicon glyphicon-remove'></span>
                                        <span class="icon-label">Delete</span>
                                    </a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}