socialProject/groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'
urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug:slug>', views.SingleGroup.as_view(), name='single'),
    path('join/<slug:slug>', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug:slug>', views.LeaveGroup.as_view(), name='leave'),
]

socialProject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path('new/', views.CreatePost.as_view(), name="create"),
    path('by/<str:username>/', views.UserPost.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name="single"),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name="delete")
]

socialProject/socialProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.testpage, name="test"),
    path('thanks/', views.thankspage, name="thanks"),
    path('groups/', include('groups.urls', namespace="groups")),
    path('posts/', include('posts.urls', namespace="posts")),
]

socialProject/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse

import misaka

User = get_user_model()
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs ):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ['name']
    

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='group_members', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta :
        unique_together = ('group', 'user')

socialProject/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404

from .models import Group, GroupMember

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        try :
            GroupMember.objects.create(user=request.user, group=group)
        except :
            # already a member
            print("Already a member")
        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        try :
            GroupMember.objects.filter(user=request.user, group__slug=self.kwargs.get('slug')).get().delete()
        except :
            print("Error")
            # already not a member
        return super().get(request, *args, **kwargs)

socialProject/groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block bodyblock %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>

{% endblock %}

socialProject/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
    <h1>{{group.name}}</h1>
    <h2>Member Count : {{group.members.count}}</h2>

    <div class="content">
    {% comment %}
        {% if user in group.members.all %}
            <a class="btn btn-danger btn-lg btn-fill" href="{% url 'groups:leave' slug=group.slug %}">Leave</a>
        {% else %}
            <a class="btn btn-success btn-lg btn-fill" href="{% url 'groups:join' slug=group.slug %}">Join</a>
        {% endif %}
    {% endcomment %}
    </div>
{% endblock %}

{% block group_content %}

<div class="col-md-10">
    {% if group.posts.count == 0 %}
        <h3>No posts in this group yet!</h3>
    {% else %}
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %}
        {% endfor %}
    {%endif%}
</div>

{% endblock %}

socialProject/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}


{% block pregroup %}{% endblock %}

{% block group_content %}
    <h2> Create a group : </h2>

    <form action="{% url 'groups:create' %}" method="post" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-success btn-large" value="Create!"></input>
    </form>
{% endblock %}

{% block postgroup %}{% endblock %}

socialProject/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2>Welcome back 
                    <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}} !</a>
                </h2>
            {% endif %}
            <h2>Groups</h2>
            <p> Here are the groups available : </p>
        </div>

        {% if user.is_authenticated %}
            <a href="{% url 'groups:create' %}" class = "btn btn-md btn-fill btn-primary">Create a Group</a>
        {% endif %}
    </div>

{% endblock %}

{% block group_content %}
    <div class="col-md-10">
        <div class="list-group">
            {% for group in object_list %}
                <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item">
                    <h3 class="title list-group-item-heading">{{group.name}}</h3>
                    <div class="listgroup-item-text">
                        {{group.description_html|safe}}
                        <div class="row">
                            <div class="col-md-4">
                                <span class="badge">{{group.members.count}}</span> Member{{group.members.count|pluralize}}
                            </div>
                            <div class="col-md-4">
                               <span class="badge">{{group.posts.count}}</span> Post{{group.posts.count|pluralize}}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}